### ISSUE TITLE
custom gatsby-config.js does not work.

### ISSUE THREAD

**Issue by nikitpatel24** [doczjs/docz#1078]
## Bug Report

**Describe the bug**

custom gatsby-config.js does not work. The project is simply compiled with default settings and generates only 404 pages with errors.

Even the custom files path is ignored.

**To Reproduce**
This occurred when using additional plugin by adding to  gatsby-config.js  in project root folder.

`
module.exports = {
  plugins: ['gatsby-plugin-resolve-src', 'gatsby-plugin-sass']
};`

```shell
(EnsureResources, ) TypeError: Cannot read property 'page' of undefined

Stack trace:
TypeError: Cannot read property 'page' of undefined
at Object.children (http://127.0.0.1:7000/commons.js:50856:2044)
at EnsureResources.render (http://127.0.0.1:7000/commons.js:50391:323)
at EnsureResources.componentRender [as render] (http://127.0.0.1:7000/commons.js:44060:64)
at finishClassComponent (http://127.0.0.1:7000/commons.js:27798:31)
at updateClassComponent (http://127.0.0.1:7000/commons.js:27753:24)
at beginWork$1 (http://127.0.0.1:7000/commons.js:29264:16)
at beginWork$$1 (http://127.0.0.1:7000/commons.js:33952:14)
at performUnitOfWork (http://127.0.0.1:7000/commons.js:32967:12)
at workLoopSync (http://127.0.0.1:7000/commons.js:32944:22)
at renderRoot (http://127.0.0.1:7000/commons.js:32637:11)
at scheduleUpdateOnFiber (http://127.0.0.1:7000/commons.js:32178:22)
at scheduleRootUpdate (http://127.0.0.1:7000/commons.js:35078:3)
at updateContainerAtExpirationTime (http://127.0.0.1:7000/commons.js:35106:10)
at updateContainer (http://127.0.0.1:7000/commons.js:35195:10)
at http://127.0.0.1:7000/commons.js:35722:7
at unbatchedUpdates (http://127.0.0.1:7000/commons.js:32446:12)
at legacyRenderSubtreeIntoContainer (http://127.0.0.1:7000/commons.js:35721:5)
at render (http://127.0.0.1:7000/commons.js:35850:12)
at http://127.0.0.1:7000/commons.js:50281:891
```

**Expected behavior**

custom config should work.
Could be a problem when merging the custom object with the original object.

**Environment**

* OS: MacOS
* Node/npm version: 12

**Comment by hvsy** [comment]
it's working like this

```javascript

module.exports = { plugins: [ {},{},'gatsby-plugin-resolve-src', 'gatsby-plugin-sass'] };


```

**Comment by jesperorb** [comment]
@nikitpatel24 

There has been some changes to how the custom gatsby config is handled in the recent RCs. Could you try upgrading to `v2.0.0-rc.47` and see it the problem still exists?

**Comment by rakannimer** [comment]
This has been resolved and added to the examples here : https://github.com/doczjs/docz/tree/master/examples/sass

Closing this, but please feel free to re-open if the issue re-occurs.
