### ISSUE TITLE
Can't install docz@next

### ISSUE THREAD

**Issue by lednhatkhanh** [doczjs/docz#1122]
## Bug Report

**Describe the bug**

npm/yarn failed to build `sharp` while installing docz@2

*A clear and concise description of what the bug is.*

**To Reproduce**

1. `npm install docz@next` or `yarn add docz@next`
2. Failed to build `sharp`

**System info**

Mac OS
npm version 6.11.3
nodejs version 10.16.3
yarn version 1.17.3

Full stacktrace:

```bash
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /Users/khanh/workspace/personal/ui-lib/node_modules/sharp
Output:
info sharp Using cached /Users/khanh/.npm/_libvips/libvips-8.8.1-darwin-x64.tar.gz
prebuild-install WARN install dlopen(/Users/khanh/workspace/personal/ui-lib/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
prebuild-install WARN install   Referenced from: /Users/khanh/workspace/personal/ui-lib/node_modules/sharp/build/Release/sharp.node
prebuild-install WARN install   Reason: image not found
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@10.16.3 | darwin | x64
gyp info find Python using Python version 2.7.10 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/khanh/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/khanh/workspace/personal/ui-lib/node_modules/sharp/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/khanh/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/khanh/Library/Caches/node-gyp/10.16.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/khanh/Library/Caches/node-gyp/10.16.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/khanh/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/khanh/Library/Caches/node-gyp/10.16.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/khanh/workspace/personal/ui-lib/node_modules/sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:25:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/khanh/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/khanh/.nvm/versions/node/v10.16.3/bin/node" "/Users/khanh/.nvm/versions/node/v10.16.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/khanh/workspace/personal/ui-lib/node_modules/sharp
```

**Comment by lednhatkhanh** [comment]
UPDATE: This issue is related to sharp, follow https://github.com/lovell/sharp/issues/1882#issuecomment-534359354 fixed it, I don't know wherever this is considered a bug or not so I will leave this open and let you decide

**Comment by rakannimer** [comment]
Hey @lednhatkhanh 

Thanks for reporting, same issue happened to me ( spent hours debugging 😅 )

Let's keep this issue open while we wait for the issue to be resolved !

**Comment by rakannimer** [comment]
Fixed upstream

**Comment by bryantsunami** [comment]
Still seem to be getting this error when I try `yarn add docz@next`
Is there some configuration change I need to make?
