### ISSUE TITLE
docz dev --port broken in v1

### ISSUE THREAD

**Issue by adam-hanna** [doczjs/docz#1126]
## Bug Report

**Describe the bug**

Running `$ docz dev --help` shows that I can pass `--port` or `-p` to dictate which port the server starts on. However, whenever I pass it something, it isn't honored.

```bash
$ docz dev -p 3001

● Docz █████████████████████████ compiling (0%)


events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**To Reproduce**

`$ docz dev -p 3001`

**Expected behavior**

Honor port flag

**Environment**

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS                                                                                                                                                    Release:        16.04
Codename:       xenial                                                                                                                                                                

$ docz --version
1.3.2
```

**Comment by rakannimer** [comment]
Hello @adam-hanna,

Thanks for reporting this, it looks like a bug in v1. 

Did you try updating to v2 : `yarn add docz@next` ?

**Comment by adam-hanna** [comment]
ah, no I haven't. I'll try v2, thanks!

**Comment by adam-hanna** [comment]
I can confirm that the port flag appears to be working on v2, however, now I am hitting a new problem. Please see below:

```bash
$ npx create-docz-app docz-bug
$ cd docz-bug
$ yarn add --dev docz@next
$ docz dev --port 3001                                                                                                                                                                                                                                                                                                                                                          Building app                                                                                                                                                                                 yarn run v1.17.3                                                                                                                                                                             $ gatsby develop --port 3001                                                                                                                                                                 /bin/sh: 1: gatsby: not found                                                                                                                                                                error Command failed with exit code 127.                                                                                                                                                     info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rakannimer** [comment]
Can you try running 

```sh
yarn docz dev --port 3001 
```

instead of 

```sh
docz dev --port 3001 
```

**Comment by adam-hanna** [comment]
Confirming that `$ yarn docz dev --port 3001` works, thanks!
