### ISSUE TITLE
using with typescript error

### ISSUE THREAD

**Issue by phyzess** [doczjs/docz#1472]
## Bug Report

**Describe the bug**

I'm trying to add docz to my existing project and use with typescript and tsx. 

When I set `typescript: true` in the doczrc.js , then run yarn docz:dev, it shows this error.

**To Reproduce**

1. yarn add docz
2. set doczrc.js
`
{typescript: true}
`
3. Change src/index.mdx to

```mdx
### Some mdx content


```

and not using any components in .mdx so far.

4. Run `yarn run docz dev`
5. Here comes the error:

```shell
`ERROR 

Failed to process data server


 ERROR 

Error: Debug Failure. False expression: Should only get Alias here.
    at Object.resolveAlias [as getAliasedSymbol] (/Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/node_modules/typescript/lib/typescript.js:33343:22)
    at Parser.getComponentInfo (/Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/node_modules/react-docgen-typescript/src/parser.ts:237:38)
    at /Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/node_modules/react-docgen-typescript/src/parser.ts:1074:20
    at Array.map (<anonymous>)
    at /Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/node_modules/react-docgen-typescript/src/parser.ts:1073:12
    at Array.reduce (<anonymous>)
    at parseWithProgramProvider (/Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/node_modules/react-docgen-typescript/src/parser.ts:1062:6)
    at Object.parseWithProgramProvider (/Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/node_modules/react-docgen-typescript/src/parser.ts:177:14)
    at /Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/dist/index.js:2271:19
    at Array.map (<anonymous>)
    at parseFiles (/Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/dist/index.js:2269:16)
    at tsParser (/Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/dist/index.js:2280:16)
    at docgen (/Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/dist/index.js:2295:30)
    at /Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/dist/index.js:2330:20
    at Object.start (/Users/phyzess/Desktop/0_Phyzess/5_GIO/gio-platform-marketing/node_modules/docz-core/dist/index.js:2364:7)
    at async Promise.all (index 0)

not finished source and transform nodes - 32.563s`
```

**Environment**

- docz version: ^2.3.1
- OS: OSX 10.15.4
- Node/yarn version: Node 12.16.2 / yarn 1.22.4
- typescript version: 3.8.3

**Comment by jesperorb** [comment]
I think it still reads some typescript-files even if you don't import them in your `.mdx`-files. Maybe try limiting the folders you are including via `doczrc.js`?`
https://www.docz.site/docs/project-configuration

Try specifying `src` or `files`
