### ISSUE TITLE
React Native config fails: TypeError: identifier.indexOf is not a function

### ISSUE THREAD

**Issue by jamie29w** [doczjs/docz#1496]
## Bug Report

**Describe the bug**

During `IN_PROGRESS` stage this error presents every time `npm run docz:dev` is run.

**To Reproduce**

In an existing React Native (non-Expo) project:

#### I deleted the docz folder and re-ran `npm run docz:dev` many times throughout this process:
1. Install docz (no caret: 2.3.1)
2. Ensure the following are installed and are at same version (^16.8.6 in my case)
  - react
  - react-art
  - react-dom
3. Install react-native-web (^0.11.7)
4. Add scripts to package.json (all 3 from docz.site)
5. Install Gatsby globally
6. Install docz globally (so scripts run)
7. Install gatsby-plugin-styled-components
8.  **Tried with and without** Create first mdx file: `src/foo-bar/index.mdx` and copy/paste `index.mdx` from docz React Native example into this folder
9. **Tried with and without** Create new folder: `src/foo-bar/Alert/` and copy/paste `Alert.jsx` and `Alert.mdx` from docz React Native example into this folder
10. Run `npm run docz:dev`
11. Run `npm i -S variant` per error instructions (even though it's already installed)

#### Add these files to root of project:
1. 
```
// doczrc.js at root of RN project
export default {
  title: 'IAMO UI Kit',
  files: ['**/*.{mdx}'],
  src: './src/foo-bar/Alert',
};
```

Also tried alt version: with `  files: '**/*.mdx',`

2.
```
// gatsby-node.js
exports.onCreateWebpackConfig = args => {
  args.actions.setWebpackConfig({
    resolve: {
      alias: {
        'react-native': 'react-native-web',
      },
    },
  });
};
```

3.
```
// gatsby-config.js
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-styled-components`,
      options: {
        // Add any options here
      },
    },
  ],
};

```

#### Rinse & Repeat Process each time:
1. Delete `docz/` auto-generated folder at root of app
2. Run `react-native start --reset-cache` each time new dependencies (or version) were installed
3. Re-run `npm run docz:dev`

**Expected behavior**

 🚀🔥✊🎉 and happy devs. Oh, and a similar build to the React Native example.

**Environment**

- docz version: 2.3.1 (no caret)
- OS: OSX 10.15.4
- Node/npm version: Node 10.15.2/NPM 6.4.1 provided by NVM

**Additional context/Screenshots**

```
➜  react-native-app git:([REDACTED]-set-up-documentation-tooling) ✗ npm run docz:dev   

> [REDACTED]/react-native-app
> docz dev


Building app
warn Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
success open and validate gatsby-configs - 0.570s
success load plugins - 0.247s
success onPreInit - 0.007s
success initialize cache - 0.006s
success copy gatsby files - 0.044s
success onPreBootstrap - 0.128s
success createSchemaCustomization - 0.003s
warn Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
success source and transform nodes - 0.185s
success building schema - 0.312s
success createPages - 0.003s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allDoczEntries" on type "Query".

If you don't expect "allDoczEntries" to exist on the type "Query" it is most likely a typo.
However, if you expect "allDoczEntries" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allDoczEntries" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: ../node_modules/gatsby-theme-docz/lib/createPagesStatefully.js:28:10

success createPagesStatefully - 0.095s
success onPreExtractQueries - 0.001s
success update schema - 0.025s
success extract queries from components - 0.067s
success write out requires - 0.008s
success write out redirect data - 0.001s
success onPostBootstrap - 0.002s
⠀
info bootstrap finished - 3.822 s
⠀
success run queries - 0.033s - 3/3 91.37/s
⠏ Building development bundle


————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
3 pages                                                         IN_PROGRESS                                                         docz-app
[REDACTED]/react-native-app/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: identifier.indexOf is not a function
    at Resolver.parse (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:301:31)
    at resolver.getHook.tapAsync (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/ParsePlugin.js:18:29)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:282:16)
    at resolver.getHook.tapAsync (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:36:14)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:282:16)
    at resolver.getHook.tapAsync (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/AliasFieldPlugin.js:53:14)
    at _next0 (eval at create (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:638:1)
    at _fn0 (eval at create (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:660:1)
    at resolver.getHook.tapAsync (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/AliasPlugin.js:74:12)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:652:1)
    at Resolver.doResolve (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/Resolver.js:282:16)
    at DescriptionFileUtils.loadDescriptionFile (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:54:17)
    at forEachBail (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:63:13)
    at args (/Users/[REDACTED]/react-native-app/node_modules/gatsby/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
```

**Comment by jamie29w** [comment]
Feel free to de-prioritize this issue or close it. I've started fresh on a clean NPM package and am having different issuew with styled-components (using css={css`...`} syntax) not updating based on context in the Playground. I can't share too much more for work reasons, so I understand if you're not able to help.
