### ISSUE TITLE
Building static HTML failed for path "/"

### ISSUE THREAD

**Issue by simachille** [doczjs/docz#1546]
In a react project i have only one .mdx file in src/components folder.
`docz dev` opens documentation
`docz build` throws this error

```
success run queries - 59.175s - 7/7 0.12/s
[                            ]   0.000 s 0/6 0% Building static HTML for pages
Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at useStaticQuery (/home/path/to/project/.docz/public/render-page.js:50650:84)
    at useDbQuery (/home/path/to/project/.docz/public/render-page.js:21100:79)
    at Layout (/home/path/to/project/.docz/public/render-page.js:18535:82)
    at d (/home/path/to/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/home/path/to/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/home/path/to/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/home/path/to/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/home/path/to/project/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Module../.cache/static-entry.js.__webpack_exports__.default (/home/path/to/project/.docz/public/render-page.js:50812:28)
    at /home/path/to/project/node_modules/gatsby/dist/utils/worker/render-html.js:28:36
    at Promise._execute (/home/path/to/project/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/home/path/to/project/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/home/path/to/project/node_modules/bluebird/js/release/promise.js:103:10)
    at /home/path/to/project/node_modules/gatsby/dist/utils/worker/render-html.js:24:47
    at tryCatcher (/home/path/to/project/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/path/to/project/node_modules/bluebird/js/release/map.js:68:38)
failed Building static HTML for pages - 6.372s

 ERROR #95313

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  32 |   if (ctx && !ctx.entry && isIndex) return db.entries.find(eqIndex)
  33 |   const filepath = get('entry.filepath', ctx)
> 34 |   return db.entries.find(propEq('value.filepath', filepath))
     |                     ^
  35 | }
  36 |
  37 | const includesTransclusion = (db, props) => {


  WebpackError: TypeError: Cannot read property 'find' of undefined
````
How to fix it.
Thanks

**Comment by wo2095296** [comment]
I'm having the same problem. How do I fix it?
