### ISSUE TITLE
First time, lots of errors

### ISSUE THREAD

**Issue by kud** [doczjs/docz#1574]
## Question

It's the first time I try docz on a project and this is what I've got (my `node_modules` and `package-lock.json` were clean)

```
npm run docz:dev

> lois-webapp@4.63.1 docz:dev my-project
> docz dev


Building app
my-project/node_modules/gatsby-recipes/node_modules/graphql/jsutils/instanceOf.js:28
      throw new Error("Cannot use ".concat(className, " \"").concat(value, "\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results."));
      ^

Error: Cannot use GraphQLInputObjectType "FileInput" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (my-project/node_modules/gatsby-recipes/node_modules/graphql/jsutils/instanceOf.js:28:13)
    at isInputObjectType (my-project/node_modules/gatsby-recipes/node_modules/graphql/type/definition.js:168:34)
    at typeMapReducer (my-project/node_modules/gatsby-recipes/node_modules/graphql/type/schema.js:290:41)
    at Array.reduce (<anonymous>)
    at typeMapReducer (my-project/node_modules/gatsby-recipes/node_modules/graphql/type/schema.js:285:34)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (my-project/node_modules/gatsby-recipes/node_modules/graphql/type/schema.js:145:28)
    at Object.<anonymous> (my-project/node_modules/gatsby-recipes/dist/graphql-server/server.js:223:16)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

success open and validate gatsby-configs - 0.847s
success load plugins - 1.176s
success onPreInit - 0.043s
success initialize cache - 0.011s
success copy gatsby files - 0.076s
success onPreBootstrap - 0.046s
success createSchemaCustomization - 0.005s
success Checking for changed pages - 0.003s
success source and transform nodes - 3.265s

 ERROR

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: Date.'. Stacktrace was 'Error: Cannot create as TypeComposer the following value: Date.
    at SchemaComposer.createTempTC (my-project/node_modules/graphql-compose/lib/SchemaComposer.js:365:11)
    at SchemaComposer.addAsComposer (my-project/node_modules/graphql-compose/lib/SchemaComposer.js:563:27)
    at createSchemaComposer (my-project/node_modules/gatsby/src/schema/schema-composer.js:16:18)
    at build (my-project/node_modules/gatsby/src/schema/index.js:104:26)
    at buildSchema (my-project/node_modules/gatsby/src/services/build-schema.ts:19:3)'

⠇ building schema
````

**Comment by kud** [comment]
And when I do it on a fresh project:

```
npx create-docz-app my-docz-app
npx: installed 1 in 2.027s
Could not locate an example named "basic". Please check your spelling and try again.
```

**Comment by cgpro** [comment]
Try to update the dependencies. After the update, it worked for me.

**Comment by devthedevel** [comment]
I'm also getting the same issue. The only difference is that I added docz as a dependency and didn't use create-docz-app. I've got the latest versions for react, and react-dom (17.0.1 at the moment). Its just stuck on building schema.
