### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by ayntee** [doczjs/docz#1582]
## Question
During the build (`npm run build`), I am receiving `Cannot read property 'includes' of undefined` error.

**Description**

Debug logs:
```log
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/bin/npm',
0 verbose cli   'run',
0 verbose cli   'build',
0 verbose cli   '--',
0 verbose cli   '--prefix-paths'
0 verbose cli ]
1 info using npm@7.0.3
2 info using node@v15.0.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/ayntee/Discordeno/docs/.docz/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/chroventer/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session 75f02de8f4a8dd75
20 timing npm:load Completed in 27ms
21 timing command:run-script Completed in 10817ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:63:27)
22 verbose stack     at ChildProcess.emit (node:events:327:20)
22 verbose stack     at maybeClose (node:internal/child_process:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
23 verbose cwd /home/ayntee/Discordeno/docs/.docz
24 verbose Linux 5.4.0-52-generic
25 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--" "--prefix-paths"
26 verbose node v15.0.1
27 verbose npm  v7.0.3
28 error code 1
29 error path /home/ayntee/Discordeno/docs/.docz
30 error command failed
31 error command sh -c gatsby build "--prefix-paths"
32 verbose exit 1
```

```log
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
1 info using npm@7.0.3
2 info using node@v15.0.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/ayntee/Discordeno/docs/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/chroventer/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session 6288334ef6e295c7
20 timing npm:load Completed in 17ms
21 timing command:run-script Completed in 13216ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:63:27)
22 verbose stack     at ChildProcess.emit (node:events:327:20)
22 verbose stack     at maybeClose (node:internal/child_process:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
23 verbose pkgid discordeno@2.0.0
24 verbose cwd /home/ayntee/Discordeno/docs
25 verbose Linux 5.4.0-52-generic
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
27 verbose node v15.0.1
28 verbose npm  v7.0.3
29 error code 1
30 error path /home/ayntee/Discordeno/docs
31 error command failed
32 error command sh -c docz build
33 verbose exit 1
```

**Comment by Yegor-IM** [comment]
Any update on this? I'm facing the same error.

**Comment by NightFox7** [comment]
I am facing the same error. Any updates ?
