### ISSUE TITLE
Crash con project init with typescript

### ISSUE THREAD

**Issue by amatiasq** [doczjs/docz#1650]
## Bug Report

Crash on project init

**To Reproduce**

1. Run `npx create-docz-app docz-ts --example typescript`

```sh
~/ssg-comparison> npx create-docz-app docz-ts --example typescript
Need to install the following packages:
  create-docz-app
Ok to proceed? (y) 
Creating a new Docz app in /Users/anon/ssg-comparison/docz-ts.

Downloading files for example typescript. This might take a moment.


Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: e.destroy is not a function
    at /Users/anon/.npm/_npx/f6e6de91721365f0/node_modules/create-docz-app/dist/index.js:2:35630
    at Array.forEach (<anonymous>)
    at /Users/anon/.npm/_npx/f6e6de91721365f0/node_modules/create-docz-app/dist/index.js:2:35573
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
```

**Comment by renatobenks** [comment]
closing thiis because we don't officially support `create-docz-app`, so we strongly recommend you to add docz directly as a dependency instead, or then, open this issue on https://github.com/rakannimer/create-docz-app. Anyways, try to follow the getting started steps from our site on https://docz.site, or on https://github.com/doczjs/docz#getting-started
