### ISSUE TITLE
The interface is not showing

### ISSUE THREAD

**Issue by codeswithroh** [doczjs/docz#1690]
## Bug Report

**The bug**
While starting a new docz project I am faced with a ton of errors which is mainly caused due to the wrong imports in the docz module itself.

**To Reproduce**

1. use `npx create-react-app doczDemo`
2. use `rm src/*`
2. Change src/index.mdx to

```mdx
---
name: Hello World
route: /
---

# Hello world from Docz!
```

4. Run npm run docz dev
5. See error in terminal

```shell
Building app
internal/modules/cjs/loader.js:331
      throw err;
      ^

Error: Cannot find module '/home/rohit/Projects/docz-blog/node_modules/remark-mdx/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:680:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/rohit/Projects/docz-blog/node_modules/gatsby-recipes/dist/graphql-server/server.js:52:17)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/rohit/Projects/docz-blog/node_modules/remark-mdx/package.json',
  requestPath: 'remark-mdx'
}


success open and validate gatsby-configs - 0.703s
success load plugins - 0.303s
success onPreInit - 0.033s
success initialize cache - 0.008s
success copy gatsby files - 0.039s
success onPreBootstrap - 0.043s
success createSchemaCustomization - 0.003s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.261s
success building schema - 0.457s
info Total nodes: 48, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.008s
success Checking for changed pages - 0.004s
success createPagesStatefully - 0.411s
success update schema - 0.060s
success write out redirect data - 0.003s
success onPostBootstrap - 0.003s
info bootstrap finished - 5.174s
success onPreExtractQueries - 0.003s
success extract queries from components - 0.092s
success write out requires - 0.007s
success run page queries - 0.027s - 1/1 37.00/s

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

eslint.CLIEngine is not a constructor

File: .cache/polyfill-entry.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

eslint.CLIEngine is not a constructor

File: .cache/app.js

failed Building development bundle - 2.280s
success building schema - 0.225s
info Total nodes: 52, SitePage nodes: 5 (use --verbose for breakdown)
success createPages - 0.004s
success Checking for changed pages - 0.001s
success update schema - 0.035s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.035s
success write out requires - 0.002s
```

**Expected behavior**

The above error is shown.

**Environment**

- docz version: ^2.3.1
- OS: Ubuntu 20.04.3 LTS
- Node/npm version: 14.0.0

**Comment by prxg22** [comment]
It seems `docz` or one of its dependencies doesn't support `eslint@8.0.0` yet.
Have you found any solution instead or did you downgraded `eslint`?
