### ISSUE TITLE
Trying 1.0.0-rc.3 — a few bunndling (?) errors

### ISSUE THREAD

**Issue by kizu** [doczjs/docz#705]
Hi! I'm trying to migrate from the `latest` to the `next`, but getting a bunch of errors, after working around one another emerges, all quite similar, several examples:

``` 
There was an error loading your config:

%secretproject%/node_modules/@babel/runtime-corejs2/helpers/esm/objectSpread.js:1
(function (exports, require, module, __filename, __dirname) { import _Object$getOwnPropertyDescriptor from "../../core-js/object/get-own-property-descriptor";
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._compile (%secretproject%/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (%secretproject%/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (%secretproject%/doczrc.js:10:45)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (%secretproject%/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

and 

```
%secretproject%/node_modules/@babel/runtime-corejs2/helpers/esm/taggedTemplateLiteral.js:1
(function (exports, require, module, __filename, __dirname) { import _Object$defineProperties from "../../core-js/object/define-properties";
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
 @ ./components/ui/Icon/Readme.mdx 1:1133-1169 1:2451-2456 1:5893-5898 1:7898-7903 1:7974-7979 1:8007-8012
 @ ./.docz/app/imports.js
 @ ./.docz/app/root.jsx
 @ ./.docz/app/index.jsx
 @ multi ./.docz/app/index.jsx
    at Promise (%secretproject%/node_modules/docz-core/dist/index.js:1291:27)
```

First problem was when I had an object spread in my docz config, the second was when trying to use tagged template literal. Seems like there is probably some bundling error most likely?

(anyway, great work on Docz, it is a really nice project!)

**Comment by nicholasess** [comment]
@kizu Can you try run with yarn command?

**Comment by kizu** [comment]
@nicholasess Mmm, this is result of running a yarn command already, this is also on a project (private, so can't show the repo & source) which already works with docz `^0.13.7` which works perfectly, but after bumping to `1.0.0-rc.3` fails to build.

This is either a regression that should be fixed, or something that is not yet mentioned in the migration guide.

**Comment by ivan-dalmet** [comment]
Any chance that the files that fail with template literal are outside the docz source folder? 
Because I fixed a similar problem by changing the src folder in docz config.

**Comment by kizu** [comment]
Hmm, I'll try to check it out, but I didn't have it defined in my config, and it is strange that there was a problem with the `doczrc.js` file itself which is in the root of the project.

**Comment by pedronauck** [comment]
Try to remove your `node_modules`, `yarn.lock` and `.docz`, this can help!

**Comment by kizu** [comment]
Just tried it — didn't help :(
