### ISSUE TITLE
Error: duplicate plugin/preset detected

### ISSUE THREAD

**Issue by akharkhonov** [doczjs/docz#716]
## Bug Report

```shell
 ERROR  Failed to compile with 1 errors                                       10:26:42 AM

 error  in ./.docz/app/index.jsx

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
    at assertNoDuplicates (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/config-descriptors.js:205:13)
    at createDescriptors (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
    at createPluginDescriptors (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/work/projects/tg-octopus/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/work/projects/tg-octopus/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/work/projects/tg-octopus/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/Users/work/projects/tg-octopus/node_modules/babel-loader/lib/index.js:5:194)
    at /Users/work/projects/tg-octopus/node_modules/babel-loader/lib/index.js:5:364

 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./.docz/app/index.jsx
```

doczrc.js
```
module.exports = {
  modifyBabelRc: babelrc => Object.assign({}, babelrc, { plugins: [] }),
  typescript: true,
  menu: ['Home', 'Components']
};
```

[package.json](https://gist.github.com/akharkhonov/5041c6a20b7ce10a1ccf4ec898fa5537)

**Environment**

* OS: Mojave 10.14
* Node/yarn version: Node 11.10/yarn 1.15.2

**Comment by doasync** [comment]
Try `console.log` to find duplicate plugin/preset:
```js
module.exports = {
  modifyBabelRc: babelrc => console.log(babelrc),
};
```
It can be `react-hot-loader/babel`
