### ISSUE TITLE
[v2.0.0-rc.1] Crashes with TypeError [ERR_INVALID_CALLBACK] with Typescript and Windows

### ISSUE THREAD

**Issue by kalynrobinson** [doczjs/docz#993]
## Bug Report

`yarn docz:dev` fails to start with the errors: 
* `UNHANDLED REJECTION Callback must be a function`
* ` Error: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function`

**To Reproduce**

1. Install `docz@next` on a fresh create-react-app
2. Run `yarn docz:dev`

3. The following warning is repeatedly outputted:

```shell
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeStatsCallback (fs.js:178:11)
    at ReaddirpStream.fs.lstat (fs.js:905:14)
    at ReaddirpStream._statMethod (internal/util.js:280:30)
    at ReaddirpStream._stat (C:\Users\Kalyn Robinson\Documents\Development\aap\skeleton\node_modules\docz-core\node_modules\readdirp\index.js:171:19)
    at ReaddirpStream._formatEntry (C:\Users\Kalyn Robinson\Documents\Development\aap\skeleton\node_modules\docz-core\node_modules\readdirp\index.js:186:28)
    at Promise.all.files.map.dirent (C:\Users\Kalyn Robinson\Documents\Development\aap\skeleton\node_modules\docz-core\node_modules\readdirp\index.js:150:65)
    at Array.map (<anonymous>)
    at ReaddirpStream._exploreDirectory (C:\Users\Kalyn Robinson\Documents\Development\aap\skeleton\node_modules\docz-core\node_modules\readdirp\index.js:150:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

4. before it eventually fails:

```shell
UNHANDLED REJECTION Callback must be a function

  Error: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

  - util.js:280 ReaddirpStream._statMethod
    internal/util.js:280:30

  - index.js:171 ReaddirpStream._stat
    [.docz]/[docz-core]/[readdirp]/index.js:171:19

  - index.js:186 ReaddirpStream._formatEntry
    [.docz]/[docz-core]/[readdirp]/index.js:186:28

  - index.js:150 Promise.all.files.map.dirent
    [.docz]/[docz-core]/[readdirp]/index.js:150:65

  - Array.map

  - index.js:150 ReaddirpStream._exploreDirectory
    [.docz]/[docz-core]/[readdirp]/index.js:150:45
```

**Expected behavior**

`yarn docz:dev` successfully starts up

**Environment**

* OS: Windows 10
* Node/npm version: 
  * Node v10.3.0
  * Yarn v1.12.3

**Comment by jesperorb** [comment]
@kalynrobinson Does this still happen with the latest rc? `v2.0.0-rc53`

**Comment by kalynrobinson** [comment]
This is resolved in later versions, thanks.
